<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Materi_model extends CI_Model
{

    public $table = 'dokumen';
    public $id = 'id_dokumen';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function jumlah_data(){
        return $this->db->get($this->table)->num_rows();
    }
    function data($number,$offset){
        return $query = $this->db->get($this->table,$number,$offset)->result();       
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_dokumen', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_dokumen', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    public function listing()
    {
        $this->db->select('*');
        $this->db->from('dokumen');
        $this->db->order_by('id_dokumen', 'DESC');
        $query = $this->db->get();
        return $query->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file dokumen_model.php */
/* Location: ./application/models/dokumen_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-24 19:34:19 */
/* http://harviacode.com */